### ISSUE TITLE
Forward algorithm issue - models/model.py

### ISSUE THREAD

**Issue by ostapen** [alexa/alexa-end-to-end-slu#2]
Hi, 
I am running your code with some custom-created splits for the FSC dataset. Running lines 123 and 135 of **forward()** and **forward_text()**, respectively, in the **models/model.py** file causes the following error message: 
`Traceback (most recent call last):`
  `File "train.py", line 35, in <module>`
   ` runner.train()`
  `File ".../alexa-end-to-end-slu/experiments/experiment_base.py", line 68, in train`
    `train_loss, train_acc = self.train_step(batch)`
  `File ".../alexa-end-to-end-slu/experiments/experiment_base.py", line 121, in train_step`
   ` metrics = self.compute_loss(batch)`
  `File ".../alexa-end-to-end-slu/experiments/experiment_triplet.py", line 111, in compute_loss`
    `output_pos = self.model(input_text=batch['encoded_text2'],`
  `File "/home/aostapen/miniconda3/envs/cs2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__`
    `result = self.forward(*input, **kwargs)`
  `File ".../alexa-end-to-end-slu/models/model.py", line 108, in forward`
    `return **self.forward_text(input_text, text_lengths)**`
  `File ".../alexa-end-to-end-slu/models/model.py", line 137, in forward_text`
    `**text_logits = self.classifier(text_embedding)**`
  `File "/home/aostapen/miniconda3/envs/cs2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__`
    `result = self.forward(*input, **kwargs)`
  `File "/home/aostapen/miniconda3/envs/cs2/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 87, in forward`
    `return F.linear(input, self.weight, self.bias)`
  `File "/home/aostapen/miniconda3/envs/cs2/lib/python3.8/site-packages/torch/nn/functional.py", line 1368, in linear`
    **`if input.dim() == 2 and bias is not None:**`
`**AttributeError: 'str' object has no attribute 'dim'**`

This is because _text_embedding_ is actually saved as the key 'pooler_output' returned in the BertModel forward(). Perhaps these lines should be: 
`_, text_embedding = self.bert(input_ids=input_text, attention_mask=attn_mask)[:2]`

Thanks in advance.

**Comment by zhengqing187** [comment]
Hi, do you get the complete.csv file? I meet the same problem as you.Could you please share your Snips dataset?
